title: Welcome to uBlahaj :3


properties:
  mode: "run-once"
  path: "~/.config/yafti/last-run"


screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: Welcome to uBlahaj :3
      description: |
        I'm gonnya halp chu set up youw system UwU

  check-no-fedora-flatpak:
    source: yafti.screen.consent
    values:
      title: Wemoving fedora flatpaks?
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        Fedora flatpak wemote was found :c Do you want to weplace it with flathub? This is wequiwed fow yafti to nyanstall flatpaks, and this will also wemove all installed flatpaks.
      actions:
        - run: flatpak remove --noninteractive --all && flatpak remote-delete --system fedora && flatpak remote-delete --user fedora && flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Nyo flathub repo OwO
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        Flathub wemote is nyot installed :c Do you want to nyanstall it? :3 This wequiwed fow yafti to nyanstall flatpaks
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  applications:
    source: yafti.screen.package
    values:
      title: Kewl apps to install :3
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        KDE Gear:
          description: KDE Apps for KDE fans UwU
          default: true
          packages:
            - KCalc: org.kde.kcalc
            - Krita: org.kde.krita
            - Gwenview: org.kde.gwenview
            - Okular: org.kde.okular
        Intewnet:
          description: Intewnet stuff for shonks on keyboawd OwO
          default: true
          packages:
            - Librewolf: io.gitlab.librewolf-community
            - Firefox: org.mozilla.firefox
            - Fluffychat: im.fluffychat.Fluffychat
            - NewsFlash: io.gitlab.news_flash.NewsFlash
            - Thunderbird: org.mozilla.Thunderbird
        Multimedia and Office:
          description: Things to watch animes :3 But also bowing office stuff TwT
          default: true
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - VLC: org.videolan.VLC
        Gaming:
          description: FUUUUUUUUUUUUUUN OwO
          default: true
          packages:
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - The cwtically acclaimed MMOWPG Final Fantasy XIV (XIVLauncher): dev.goats.xivlauncher
            - MangoHud: org.freedesktop.Platform.VulkanLayer.MangoHud
        Tools:
          description: The best categowy UwU
          default: true
          packages:
            - Podman Desktop: io.podman_desktop.PodmanDesktop
            - Fedowa Media Writew: org.fedoraproject.MediaWriter
            - Remmina: org.remmina.Remmina

  omz-consent:
    source: yafti.screen.consent
    values:
      title: ohmyzsh nyanstallation
      condition:
        run: |
          [ -d "$HOME/.oh-my-zsh" ] || echo "ohmyzsh is not installed"
      description: |
        uBlahaj comes with zsh pweinstalled. Do you want to install ohmyzsh like a kewl shark? You can also do that later with ujust
      actions:
        - run: /usr/libexec/toggle_omz.sh install -n

  sharkonfig-consent:
    source: yafti.screen.consent
    values:
      title: sharkonfig nyanstallation
      condition:
        run: |
          [ -d "$HOME/.config/nvim/lua/shork" ] || echo "sharkonfig is not installed"
      description: |
        Do you want to nyanstall sharkonfig user configs? These are a collection of dotfiles made for uBlahaj.
      actions:
        - run: git clone --recurse-submodules https://github.com/Sharkitty/sharkonfig.git $HOME/sharkonfig && python3 $HOME/sharkonfig/scripts/copy.py && rm -rf $HOME/sharkonfig

  final-screen:
    source: yafti.screen.title
    values:
      title: Congwats!
      description: Youw system is nyow a hapi shonk :3
      links:
        - "Install Mowe kewl apps (Open Discover)":
            run: /usr/bin/plasma-discover
        - "Check out uBlahaj wepositowy":
            run: /usr/bin/xdg-open https://github.com/Sharkitty/uBlahaj
        - "Check out Universal Blue (upstweam image)":
            run: /usr/bin/xdg-open https://universal-blue.org/
        - "Check out BlueBuild (used to make this image)":
            run: /usr/bin/xdg-open https://blue-build.org/
        - "Fedora official website":
            run: /usr/bin/xdg-open https://fedoraproject.org/
